### ISSUE TITLE
Calling plot.destroy() results in unexpected exception

### ISSUE THREAD

**Issue by cmnzs** [unchartedsoftware/lumo#6]
In one case, we disable panning and zooming so don't add event handlers to a map plot.

```
if (!this.disableControls) {
     this.map.on('zoomend', this.zoomEnd);
     this.map.on('panend', this.panEnd);
}
....
   if (this.disableControls) {
            this.map.disableZooming();
            this.map.disablePanning();
            this.map.zoomToPosition(DEFAULT_ZOOM_DISABLED_CONTROL, { x: DEFAULT_CENTER, y: DEFAULT_CENTER }, false);
         }
```
However, later, when cleaning up the view:
```
this.map.destroy();
```
Throws this exception:
![image](https://user-images.githubusercontent.com/1922731/35449436-fe02e69c-028a-11e8-8790-a64b6ab60306.png)

In Plot.js
```
this[HANDLERS].forEach(handler => {
	handler.disable();
});
```

So in DomHandler.js, this is causing the problem:
```
	disable() {
		if (!this.enabled) {
			throw 'Handler is already disabled';
		}
		this.enabled = false;
	}
```

**Comment by cmnzs** [comment]
Also, the comments referencing
`* @returns {ZoomHandler} The handler object, for chaining.` 
seem to be out of date (in DomHandler.js)

**Comment by kbirk** [comment]
Resolved!
